#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""gui_wrap：把 compiler 产出的脚本体包装为 GUI --run 可执行脚本（B4 定稿 2026-08-29）。

三件套（pitfalls #7/#8/#9，与 tools/s4l_solve._emit_gui_rerun_script 同源）：
- XCore.GetApp() 上下文自适应：GUI 进程内直接取 app，取不到（headless）回退
  run_application()；
- 日志写文件：stdout/stderr 重定向到 log_path（buffering=1 行缓冲），GUI 下
  stdout 不可见，print("REPORT|...") 必须落文件；
- os._exit(0) 退出：GUI --run 模式下脚本结束后进程必须退出；脚本体抛异常时
  经 sys.excepthook 落栈后 os._exit(1)。

纯发射器：参数 → 代码字符串，不 import s4l_v1（py_compile 只解析不执行）。
"""

from __future__ import annotations


def emit_gui_script(body: str, log_path: str) -> str:
    """把脚本体包装为可在 ``Sim4LifeLight.exe --minimized --run <script>`` 下
    运行的完整脚本。

    body 原样逐字节嵌入（compiler 产物，以 document.New() 等 s4l_v1 调用开头）；
    log_path 为运行时绝对路径，反斜杠统一转成正斜杠后嵌入，避免 Windows
    路径炸转义（如 \\t、\\r 被吞）。
    """
    safe_log = log_path.replace("\\", "/")
    return f'''# -*- coding: utf-8 -*-
# Auto-generated by research-agent gui_wrap (GUI --run wrapper).
import os
import sys
import traceback

# 日志写文件（pitfall #8：GUI stdout 不可见，REPORT 必须落文件）
_log = open(r"{safe_log}", "w", buffering=1)
sys.stdout = _log
sys.stderr = _log


def _excepthook(exc_type, exc, tb):
    # 脚本体抛异常也要落栈后退出 GUI 进程（pitfall #9）
    traceback.print_exception(exc_type, exc, tb)
    _log.flush()
    os._exit(1)


sys.excepthook = _excepthook

# 上下文自适应（pitfall #7）：GUI 进程内 XCore.GetApp()，否则回退 headless
try:
    import XCore
    _app = XCore.GetApp()
    if _app is None:
        raise ImportError("XCore.GetApp() returned None")
except ImportError:
    from s4l_v1._api.application import run_application
    _app = run_application()

# ===== 脚本体（compiler 产物，原样嵌入）=====
{body}
# ===== 脚本体结束 =====

try:
    _log.flush()
    _log.close()
except Exception:
    pass
os._exit(0)
'''
