#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""s4l_solve 工具：基准复算编排 + 物理验证（B3 定稿 2026-08-03）。

链路：生成 GUI --run 重跑脚本 → Sim4LifeLight.exe --minimized --run（继承云端
license，headless 无 QS_SOLVER）→ h5py 直读 Output.h5 → 双 ground truth 判定：
- 基准复算：重跑结果 vs 基准 Output.h5，逐分量强场相对误差（pass ≤ 1%，实测 0.000%）；
- 方案 A 线性验证：激励幅值 ×N 重跑 vs 基准，|E| 中位比值应 ≈ N（pass ≤ 5%）。

工程纪律（pitfalls）：基准 Output.h5 重跑会被同名覆盖——先备份再复算（#29）；
GUI stdout 不可见——日志写文件（#8）；os._exit(0) 退出（#9）；Popen + 超时
taskkill /F /T 杀整棵树（#31）；license 单座——S4L 任务严格串行（#3）。

判定逻辑与编排分离：_judge 纯函数可单测。
"""

from __future__ import annotations

import shutil
import subprocess
import time
from pathlib import Path

from research_agent.config import SETTINGS
from research_agent.descriptor import ToolDescriptor, ToolSpec
from research_agent.s4lmodel import h5compare

# 本机基准模型（2026-08-02 探针确认：R1 3.6M dofs，~90s 求解）
DEFAULT_BENCHMARK_SMASH = "D:/TMS/BME/BMEN16/BMEN16.smash"

RECOMPUTE_PASS_TOL = 0.01   # 复算：同一模型同一求解器，理论偏差≈0
LINEARITY_PASS_TOL = 0.05   # 方案 A：线性区 |E| ∝ I，中位比值容差 ±5%


def _judge(rel_errs: list[float], pass_tol: float, partial_tol: float | None = None) -> str:
    """三档判定：全部 ≤pass_tol → pass；否则全部 ≤partial_tol → partial；否则 fail。"""
    if not rel_errs:
        return "fail"
    if all(e <= pass_tol for e in rel_errs):
        return "pass"
    if partial_tol is not None and all(e <= partial_tol for e in rel_errs):
        return "partial"
    return "fail"


def _emit_gui_rerun_script(
    smash_path: str,
    sim_name: str,
    log_path: str,
    amplitude_scale: float | None = None,
    backup_dir: str | None = None,
) -> str:
    """生成 GUI --run 重跑脚本（在 GUI 进程内执行，继承 license）。

    三件套（pitfalls #7/#8/#9）：XCore.GetApp() 上下文自适应（不调
    run_application）、日志写文件（buffering=1）、os._exit(0) 退出。
    amplitude_scale 非 None 时发射方案 A 扰动块（已知边界：GUI 设置对象不可写，
    读回验证 RUN|SCALE|verify| + 编排层 stage=perturb 门禁兜底）。
    backup_dir 非 None 时：求解前由脚本内备份**目标 sim 的** Output.h5
    （不再全量复制结果目录——2026-08-03 磁盘事故教训：全量备份 6 轮吃了 71G）。
    """
    backup_block = ""
    if backup_dir is not None:
        backup_block = f'''
    # 只备份目标 sim 的输出（重跑同名覆盖，pitfall #29）
    _gofn = getattr(_sim, "GetOutputFileName", None)
    _out = _gofn() if callable(_gofn) else _gofn
    _p("RUN|OUTFILE|" + str(_out))
    try:
        import os as _os
        import shutil as _shutil
        if _out and _os.path.isfile(str(_out)):
            _os.makedirs(r"{backup_dir}", exist_ok=True)
            _shutil.copy2(str(_out), _os.path.join(r"{backup_dir}", _os.path.basename(str(_out))))
            _p("RUN|BACKUP|ok")
        else:
            _p("RUN|BACKUP|missing")
    except Exception as _e:
        _p("RUN|BACKUP|fail|" + repr(_e))
'''
    scale_block = ""
    if amplitude_scale is not None:
        scale_block = f'''
    # 方案 A：激励幅值扰动 ×{amplitude_scale}
    # 已知边界（2026-08-03 探针定案）：GUI 会话中加载模型的设置对象整体不可写
    # （属性直写/AmplitudeProp/清结果三假设均排除），读回验证会捕获并报 stage=perturb；
    # B4 改走 WriteInputFile→Input.h5 路线后本块应随之更新。
    _css = []
    for _attr in ("AllSettings", "Settings"):
        _getter = getattr(_sim, _attr, None)
        try:
            _cands = _getter() if callable(_getter) else _getter
            for _st in _cands or []:
                if "CurrentSource" in type(_st).__name__:
                    _css.append(_st)
        except Exception:
            pass
    _scaled = 0
    for _st in _css:
        try:
            import s4l_v1.units as _units
            _amp = _st.Amplitude
            _v = float(_amp[0]) if hasattr(_amp, "__iter__") else float(_amp)
            _new = _v * {float(amplitude_scale)!r}
            # 探针定案（2026-08-03）：GUI --run 中属性直写静默 no-op，
            # 必须走 AmplitudeProp.Value（QuantityScalar，GUI Property 系统通路）
            _prop = getattr(_st, "AmplitudeProp", None)
            if _prop is not None:
                _prop.Value = (_new, _units.Amperes)
            else:
                _st.Amplitude = (_new, _units.Amperes)
            _chk = _st.Amplitude
            _chk_v = float(_chk[0]) if hasattr(_chk, "__iter__") else float(_chk)
            _p("RUN|SCALE|verify|" + str(_chk_v))  # 读回验证：no-op 检测
            _scaled += 1
            _p("RUN|SCALE|" + str(getattr(_st, "Name", "?")) + "|" + str(_v))
        except Exception as _e:
            _p("RUN|SCALE|FAIL|" + repr(_e))
    _p("RUN|SCALE|count|" + str(_scaled))
'''
    return f'''# -*- coding: utf-8 -*-
# Auto-generated by research-agent s4l_solve (GUI --run rerun script).
import os
import traceback

_log = open(r"{log_path}", "w", buffering=1)


def _p(*args):
    print(*args, file=_log)


try:
    import XCore
    _app = XCore.GetApp()
    _p("RUN|CONTEXT|" + ("gui" if _app is not None else "headless"))

    import s4l_v1.document as document
    document.Open(r"{smash_path}")
    _sim = None
    for _s in document.AllSimulations:
        if getattr(_s, "Name", "") == "{sim_name}":
            _sim = _s
            break
    if _sim is None:
        raise RuntimeError("sim not found: {sim_name}")
    _p("RUN|SIM|" + str(_sim.Name))
{backup_block}{scale_block}
    _sim.RunSimulation(wait=True, run_isolve_directly=True)  # Ares 路径报笼统错误，iSolve 子进程给真实错误
    _p("RUN|SOLVE|HasResults|" + str(_sim.HasResults()))
    _p("RUN|DONE")
except Exception:
    _p("RUN|ERROR")
    _p(traceback.format_exc())
finally:
    try:
        _log.close()
    except Exception:
        pass
    os._exit(0)
'''


def _s4l_run_gui(script_path: str, log_path: str, timeout_s: int = 1800) -> dict:
    """GUI --run 执行器：Sim4LifeLight.exe --minimized --run <script>。

    GUI stdout 不可见——返回日志文件内容。超时 taskkill /F /T 杀整棵进程树。
    """
    if not SETTINGS.s4l_gui or not Path(SETTINGS.s4l_gui).is_file():
        raise RuntimeError(f"S4L_GUI 未配置或不存在：{SETTINGS.s4l_gui}")
    script = Path(script_path)
    if not script.is_file():
        raise FileNotFoundError(f"脚本不存在：{script_path}")

    started = time.perf_counter()
    proc = subprocess.Popen(
        [SETTINGS.s4l_gui, "--minimized", "--run", str(script)],
        cwd=SETTINGS.s4l_home or None,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    timed_out = False
    try:
        proc.wait(timeout=max(10, int(timeout_s)))
    except subprocess.TimeoutExpired:
        timed_out = True
        try:
            subprocess.run(
                ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                capture_output=True, timeout=30,
            )
        except Exception:
            proc.kill()
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            pass
    duration = round(time.perf_counter() - started, 2)

    log = ""
    lp = Path(log_path)
    if lp.is_file():
        log = lp.read_text(encoding="utf-8", errors="replace")
    return {
        "exit_code": -9 if timed_out else proc.returncode,
        "timed_out": timed_out,
        "log": log,
        "duration_s": duration,
    }


def _snapshot_outputs(results_dir: str) -> dict[str, float]:
    """{Output.h5 路径: mtime} 快照——复算前后对比，定位被重写的输出（pitfall #29）。"""
    rd = Path(results_dir)
    if not rd.is_dir():
        return {}
    return {str(p): p.stat().st_mtime for p in rd.glob("*_Output.h5")}


def _pick_recomputed(before: dict[str, float], after: dict[str, float]) -> str | None:
    """复算后 mtime 更新（或新增）的 Output.h5；多个/零个均返回 None（异常需人工）。"""
    changed = [p for p, mt in after.items() if p not in before or mt > before[p]]
    return changed[0] if len(changed) == 1 else None


def _parse_scale_count(log: str) -> int | None:
    for line in (log or "").splitlines():
        if line.startswith("RUN|SCALE|count|"):
            try:
                return int(line.rsplit("|", 1)[1])
            except ValueError:
                return None
    return None


def _parse_scale_verify(log: str) -> list[tuple[float, float]]:
    """从日志提取 (原值, 读回值) 对——写路径 no-op 检测（探针定案 2026-08-03）。"""
    origs: list[float] = []
    verifies: list[float] = []
    for line in (log or "").splitlines():
        parts = line.strip().split("|")
        if len(parts) == 4 and parts[:2] == ["RUN", "SCALE"] \
                and parts[2] not in ("count", "verify", "FAIL"):
            try:
                origs.append(float(parts[3]))
            except ValueError:
                pass
        elif len(parts) == 4 and parts[:3] == ["RUN", "SCALE", "verify"]:
            try:
                verifies.append(float(parts[3]))
            except ValueError:
                pass
    return list(zip(origs, verifies))


def _s4l_solve_benchmark(
    smash_path: str | None = None,
    sim_name: str = "R1",
    amplitude_scale: float | None = None,
    timeout_s: int = 1800,
) -> dict:
    """基准复算编排：备份 → GUI --run 重跑 → h5py 对比 → 判定报告。

    amplitude_scale 非 None 时走方案 A 线性验证（容差 ±5%），否则复算对比（≤1%）。
    """
    started = time.perf_counter()
    smash = smash_path or DEFAULT_BENCHMARK_SMASH
    if not Path(smash).is_file():
        return {"status": "error", "stage": "input",
                "error": f"基准模型不存在：{smash}"}
    results_dir = smash + "_Results"

    notes = [
        "基准复算：同一模型同一求解器重跑，理论偏差≈0（2026-08-02 实测 0.000%）",
        "执行器：Sim4LifeLight.exe --minimized --run（GUI 进程内继承云端 license）",
        "提取：h5py 直读 Output.h5，绕过 S4L 后处理 API",
    ]

    # 1) 快照结果目录（复算后用 mtime 差分定位被重写的输出）
    before = _snapshot_outputs(results_dir)
    if not before:
        return {"status": "error", "stage": "baseline",
                "error": f"基准结果目录无 Output.h5：{results_dir}"}
    # 备份由 GUI 脚本在求解前完成——只复制目标 sim 的那一个 Output.h5
    # （2026-08-03 磁盘事故教训：全量复制结果目录 6 轮吃 71G）
    tag = int(time.time())
    backup_dir = Path(SETTINGS.artifacts_dir) / f"h5_baseline_{tag}"
    backup_dir.mkdir(parents=True, exist_ok=True)

    # 2) 生成 + 执行 GUI --run 重跑脚本（严格串行，license 单座）
    script_path = str(Path(SETTINGS.artifacts_dir) / f"s4l_rerun_{tag}.py")
    log_path = str(Path(SETTINGS.artifacts_dir) / f"s4l_rerun_{tag}.log")
    Path(script_path).write_text(
        _emit_gui_rerun_script(smash, sim_name, log_path, amplitude_scale,
                               backup_dir=str(backup_dir)),
        encoding="utf-8",
    )
    try:
        run = _s4l_run_gui(script_path, log_path, timeout_s=timeout_s)
    except Exception as exc:
        return {"status": "error", "stage": "run", "error": str(exc),
                "script_path": script_path, "log_path": log_path}

    if run["timed_out"] or "RUN|DONE" not in run["log"]:
        return {
            "status": "error", "stage": "solve",
            "error": "重跑未完成（超时或日志无 RUN|DONE）",
            "run": run, "script_path": script_path, "log_path": log_path,
            "notes": notes,
        }
    if "RUN|BACKUP|ok" not in run["log"]:
        return {
            "status": "error", "stage": "baseline",
            "error": "目标输出的基准备份未完成（见日志 RUN|BACKUP|）",
            "run": run, "script_path": script_path, "log_path": log_path,
            "notes": notes,
        }

    # 3) 方案 A 前提：扰动必须真实生效（写路径读回验证），否则对比无意义
    if amplitude_scale is not None:
        count = _parse_scale_count(run["log"])
        if not count:
            return {
                "status": "error", "stage": "perturb",
                "error": f"激励扰动未生效（RUN|SCALE|count|={count}）——"
                         "CurrentSourceSettings 枚举 API 需补探针",
                "run": run, "script_path": script_path, "log_path": log_path,
                "notes": notes,
            }
        bad = [(o, v) for o, v in _parse_scale_verify(run["log"])
               if abs(v - o * amplitude_scale) > 0.01 * abs(o * amplitude_scale)]
        if bad:
            return {
                "status": "error", "stage": "perturb",
                "error": f"激励写入被静默吞掉（读回验证失败：(原值,读回)={bad}）——"
                         "写路径需走 AmplitudeProp.Value（探针定案）",
                "run": run, "script_path": script_path, "log_path": log_path,
                "notes": notes,
            }
        notes.append(f"方案 A：{count} 个电流源幅值 ×{amplitude_scale}"
                     "（读回验证生效）")

    # 4) 定位被重写的 Output.h5 并对比其基准备份
    recomputed = _pick_recomputed(before, _snapshot_outputs(results_dir))
    if recomputed is None:
        return {
            "status": "error", "stage": "locate",
            "error": "无法唯一定位复算输出（0 个或多个 mtime 变化）",
            "run": run, "script_path": script_path, "log_path": log_path,
            "notes": notes,
        }
    baseline = str(backup_dir / Path(recomputed).name)

    if amplitude_scale is not None:
        stats = h5compare.compare_linearity(recomputed, baseline, amplitude_scale)
        verdict = _judge([stats["worst"]["ratio_rel_err_vs_scale"]],
                         LINEARITY_PASS_TOL)
        tol = {"linearity_pass": LINEARITY_PASS_TOL, "scale": amplitude_scale}
    else:
        stats = h5compare.compare_fields(recomputed, baseline)
        verdict = _judge([stats["worst"]["max_rel_err"]], RECOMPUTE_PASS_TOL)
        tol = {"recompute_pass": RECOMPUTE_PASS_TOL}

    # 对比完成即清理单文件备份（只在出错路径保留现场，防磁盘累积）
    try:
        shutil.rmtree(backup_dir, ignore_errors=True)
    except Exception:
        pass
    notes.append("基准备份为单文件级且对比后已清理（磁盘纪律 2026-08-03）")

    return {
        "status": "ok" if verdict == "pass" else "failed_verification",
        "verdict": verdict,
        "mode": "linearity" if amplitude_scale is not None else "recompute",
        "field_stats": stats,
        "tolerances": tol,
        "notes": notes,
        "smash_path": smash,
        "sim_name": sim_name,
        "recomputed_h5": recomputed,
        "baseline_h5": baseline,
        "script_path": script_path,
        "log_path": log_path,
        "run": run,
        "duration_s": round(time.perf_counter() - started, 1),
    }


DESCRIPTOR = ToolDescriptor(
    spec=ToolSpec(
        name="s4l_solve_benchmark",
        description=(
            "Sim4Life 基准复算验证：备份基准 Output.h5 → GUI --run 重跑指定仿真"
            "（继承云端 license）→ h5py 逐体素对比 → pass/partial/fail 判定。"
            "amplitude_scale 非空时做方案 A 线性缩放验证（±5%）。"
            "license 单座：调用必须严格串行，禁止与其他 S4L 任务并发。"
        ),
        parameters={
            "type": "object",
            "properties": {
                "smash_path": {"type": "string",
                               "description": "基准 .smash 路径，缺省 BMEN16"},
                "sim_name": {"type": "string", "default": "R1",
                             "description": "按 Name 选择的仿真"},
                "amplitude_scale": {"type": "number",
                                    "description": "方案 A：激励幅值缩放倍数（如 2.0）"},
                "timeout_s": {"type": "integer", "default": 1800,
                              "description": "GUI 冷启动 3-5min + 求解 ~90s，勿设太小"},
            },
            "required": [],
        },
        handler=_s4l_solve_benchmark,
    ),
    category="simulation",
    cost_hint="expensive",
    async_capable=True,
    requires=["sim4life_gui"],
    produces_artifacts=True,
)
