#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""s4l_run_script 工具：Sim4Life headless 脚本执行器。

用 Sim4Life 安装目录自带的 Python（3.6.8）以子进程方式运行 s4l_v1 脚本。
实测要点（2026-07-21 验证）：
- 脚本必须先调 run_application() 建立应用上下文（否则 doc.New() 报无 application）。
- cwd 必须设为 S4L_HOME。
- model.Create* 创建的实体自动进入活动文档；坐标用 model.Vec3。
"""

from __future__ import annotations

import subprocess
import time
from pathlib import Path

from research_agent.config import SETTINGS
from research_agent.descriptor import ToolDescriptor, ToolSpec

_BOOTSTRAP_HEADER = '''# -*- coding: utf-8 -*-
"""Auto-generated by research-agent s4l_run_script (bootstrap header)."""
from s4l_v1._api.application import run_application

_app = run_application()

'''


def build_script(body: str) -> str:
    """把 agent 生成的脚本主体包装进 headless 引导头。"""
    return _BOOTSTRAP_HEADER + body


def _s4l_write_script(body: str, filename: str = "s4l_task.py") -> dict:
    """把脚本主体（含引导头）写入 artifacts 目录，返回 {script_path}。"""
    artifacts = Path(SETTINGS.artifacts_dir)
    artifacts.mkdir(parents=True, exist_ok=True)
    safe_name = Path(filename).name or "s4l_task.py"
    if not safe_name.endswith(".py"):
        safe_name += ".py"
    path = artifacts / f"{int(time.time())}_{safe_name}"
    path.write_text(build_script(body), encoding="utf-8")
    return {"script_path": str(path)}


WRITE_DESCRIPTOR = ToolDescriptor(
    spec=ToolSpec(
        name="s4l_write_script",
        description=(
            "把 Sim4Life s4l_v1 脚本主体写入 artifacts 目录并自动加 headless 引导头"
            "（run_application 初始化），返回可传给 s4l_run_script 的脚本路径。"
        ),
        parameters={
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "description": "s4l_v1 脚本主体（不含引导头），使用 document/model/simulation API",
                },
                "filename": {"type": "string", "default": "s4l_task.py"},
            },
            "required": ["body"],
        },
        handler=_s4l_write_script,
    ),
    category="simulation",
    cost_hint="free",
    requires=[],
    produces_artifacts=True,
)


def _s4l_run_script(
    script_path: str,
    timeout_s: int = 300,
    artifacts_glob: str = "",
) -> dict:
    """执行 s4l 脚本，返回 {stdout, stderr, exit_code, duration_s, artifacts}。"""
    if not SETTINGS.s4l_python or not Path(SETTINGS.s4l_python).is_file():
        raise RuntimeError(f"S4L_PYTHON 未配置或不存在：{SETTINGS.s4l_python}")
    if not SETTINGS.s4l_home or not Path(SETTINGS.s4l_home).is_dir():
        raise RuntimeError(f"S4L_HOME 未配置或不存在：{SETTINGS.s4l_home}")
    script = Path(script_path)
    if not script.is_file():
        raise FileNotFoundError(f"脚本不存在：{script_path}")

    started = time.perf_counter()
    proc = subprocess.Popen(
        [SETTINGS.s4l_python, str(script)],
        cwd=SETTINGS.s4l_home,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    timed_out = False
    try:
        stdout, stderr = proc.communicate(timeout=max(10, int(timeout_s)))
    except subprocess.TimeoutExpired:
        # Windows 坑：kill 父进程后孙进程（S4L 内核）仍持有管道，
        # communicate() 会无限等 EOF——必须 taskkill /T 杀整棵进程树。
        timed_out = True
        try:
            subprocess.run(
                ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                capture_output=True, timeout=30,
            )
        except Exception:
            proc.kill()
        try:
            stdout, stderr = proc.communicate(timeout=30)
        except subprocess.TimeoutExpired:
            stdout, stderr = "", "killed: process tree terminated, pipes abandoned"
    duration = round(time.perf_counter() - started, 2)

    artifacts: list[str] = []
    if artifacts_glob:
        artifacts = sorted(str(p) for p in Path().glob(artifacts_glob))
    return {
        "stdout": (stdout or "")[-4000:],
        "stderr": ((stderr or "") + ("\nTIMEOUT: killed process tree" if timed_out else ""))[-2000:],
        "exit_code": -9 if timed_out else proc.returncode,
        "duration_s": duration,
        "artifacts": artifacts,
    }


DESCRIPTOR = ToolDescriptor(
    spec=ToolSpec(
        name="s4l_run_script",
        description=(
            "以 headless 方式执行 Sim4Life 建模/仿真 Python 脚本（s4l_v1 API），"
            "返回标准输出与产出文件。脚本主体应使用 s4l_v1.document/model/simulation。"
        ),
        parameters={
            "type": "object",
            "properties": {
                "script_path": {"type": "string", "description": "待执行的 .py 脚本绝对路径"},
                "timeout_s": {"type": "integer", "default": 300, "description": "超时秒数"},
                "artifacts_glob": {
                    "type": "string",
                    "default": "",
                    "description": "可选，产物文件 glob（如 artifacts/*.smash）",
                },
            },
            "required": ["script_path"],
        },
        handler=_s4l_run_script,
    ),
    category="simulation",
    cost_hint="expensive",
    async_capable=True,
    requires=["sim4life_installed"],
    produces_artifacts=True,
)
